# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PushNotificationData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_ids: List[str]=None, title: str=None, body: str=None, img_url: str=None, notification_type: str=None, variables: object=None, data: object=None):  # noqa: E501
        """PushNotificationData - a model defined in Swagger

        :param user_ids: The user_ids of this PushNotificationData.  # noqa: E501
        :type user_ids: List[str]
        :param title: The title of this PushNotificationData.  # noqa: E501
        :type title: str
        :param body: The body of this PushNotificationData.  # noqa: E501
        :type body: str
        :param img_url: The img_url of this PushNotificationData.  # noqa: E501
        :type img_url: str
        :param notification_type: The notification_type of this PushNotificationData.  # noqa: E501
        :type notification_type: str
        :param variables: The variables of this PushNotificationData.  # noqa: E501
        :type variables: object
        :param data: The data of this PushNotificationData.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'user_ids': List[str],
            'title': str,
            'body': str,
            'img_url': str,
            'notification_type': str,
            'variables': object,
            'data': object
        }

        self.attribute_map = {
            'user_ids': 'user_ids',
            'title': 'title',
            'body': 'body',
            'img_url': 'img_url',
            'notification_type': 'notification_type',
            'variables': 'variables',
            'data': 'data'
        }
        self._user_ids = user_ids
        self._title = title
        self._body = body
        self._img_url = img_url
        self._notification_type = notification_type
        self._variables = variables
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'PushNotificationData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PushNotificationData of this PushNotificationData.  # noqa: E501
        :rtype: PushNotificationData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_ids(self) -> List[str]:
        """Gets the user_ids of this PushNotificationData.


        :return: The user_ids of this PushNotificationData.
        :rtype: List[str]
        """
        return self._user_ids

    @user_ids.setter
    def user_ids(self, user_ids: List[str]):
        """Sets the user_ids of this PushNotificationData.


        :param user_ids: The user_ids of this PushNotificationData.
        :type user_ids: List[str]
        """

        self._user_ids = user_ids

    @property
    def title(self) -> str:
        """Gets the title of this PushNotificationData.


        :return: The title of this PushNotificationData.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this PushNotificationData.


        :param title: The title of this PushNotificationData.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this PushNotificationData.


        :return: The body of this PushNotificationData.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this PushNotificationData.


        :param body: The body of this PushNotificationData.
        :type body: str
        """

        self._body = body

    @property
    def img_url(self) -> str:
        """Gets the img_url of this PushNotificationData.


        :return: The img_url of this PushNotificationData.
        :rtype: str
        """
        return self._img_url

    @img_url.setter
    def img_url(self, img_url: str):
        """Sets the img_url of this PushNotificationData.


        :param img_url: The img_url of this PushNotificationData.
        :type img_url: str
        """

        self._img_url = img_url

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this PushNotificationData.


        :return: The notification_type of this PushNotificationData.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this PushNotificationData.


        :param notification_type: The notification_type of this PushNotificationData.
        :type notification_type: str
        """

        self._notification_type = notification_type

    @property
    def variables(self) -> object:
        """Gets the variables of this PushNotificationData.


        :return: The variables of this PushNotificationData.
        :rtype: object
        """
        return self._variables

    @variables.setter
    def variables(self, variables: object):
        """Sets the variables of this PushNotificationData.


        :param variables: The variables of this PushNotificationData.
        :type variables: object
        """

        self._variables = variables

    @property
    def data(self) -> object:
        """Gets the data of this PushNotificationData.


        :return: The data of this PushNotificationData.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this PushNotificationData.


        :param data: The data of this PushNotificationData.
        :type data: object
        """

        self._data = data
